FN = "BLJM_66675.c"

dis = open(FN).read()

HEADER = """/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>

#include <stdarg.h>

"""

F_DECS_HEADER = """//-------------------------------------------------------------------------
// Function declarations
"""